<?xml version="1.0" encoding="utf-8"?><Database Name="WPStatelessPoC" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=devsql;Initial Catalog=WPStatelessPoC;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WPStatelessPoCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CartItem" Member="CartItems">
    <Type Name="CartItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CartId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sku" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cart_CartItem" Member="Cart" ThisKey="CartId" OtherKey="Id" Type="Cart" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cart" Member="Carts">
    <Type Name="Cart">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Cart_CartItem" Member="CartItems" ThisKey="Id" OtherKey="CartId" Type="CartItem" />
    </Type>
  </Table>
</Database>